AllCops:
  Exclude:
    - db/migrations/*
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

# Some RSpec matchers must be used with {} syntax
Style/BlockDelimiters:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'apps/**/application.rb'

Style/Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

DoubleNegation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: 'literal'
