language: ruby
before_install:
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
      - libqt5webkit5
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - psql -c 'create database pinfluence_test;' -U postgres
  - bundle exec hanami db prepare
script:
  - xvfb-run bundle exec rspec
